#!/bin/bash


frame_exists=`emacsclient -e "(member \"$DISPLAY\" (mapcar 'terminal-name (frames-on-display-list)))" 2>/dev/null`
opts=''
#delete terminal option from options list
for arg in "$@"
do
    terminal="(-nw)|(-t)|(-tty)"
    if [[ "$arg" =~ $terminal ]]; then
        add_opts=' -t'
    else
        opts="$opts$arg"
    fi
done

if [[ "$frame_exists" = "" ]]; then #'nothing is open'
    `emacs $opts$add_opts`
elif [[ "$frame_exists" = "nil" ]]; then #'terminal is open'
    [[ "$add_opts" = "" ]] && add_opts=' -c'
    `emacsclient -e '(find-file \"$opts\")'$add_opts`
else #'frame(x-window) is open'
    `emacsclient -e '(find-file \"$opts\")'$add_opts`
fi


<< --MULTILINE-COMMENT--
#echo "arguments = $@"

#terminal="(-nw)|(-t)|(-tty)"

#[[ "$@" =~ $terminal ]] && echo "terminal"
#[[ "${@/#-nw/}" == "$@" ]] && echo "not matches nw"
#last_arg="${@: -1}"
#emacsstyle="emacsclient -e '(find-file \"$last_arg\")'"
#echo $emacsstyle
#echo "rest = ${*%${!#}} $zhopa"

frame_exists=`emacsclient -e "(member \"$DISPLAY\" (mapcar 'terminal-name (frames-on-display-list)))" 2>/dev/null`
#terminal="(-nw)|(-t)|(-tty)"
#last_opt="${@: -1}"
#rest_opts=${*%${!#}}
#opts=$@

#[[ "$@" =~ $terminal ]] && echo "terminal"
#''
#nil
#(:0)
for arg in "$@"
do
    terminal="(-nw)|(-t)|(-tty)"
    if [[ "$arg" =~ $terminal ]]; then
        add_opts=' -t'
    else
        opts="$opts$arg"
    fi
done

if [[ "$frame_exists" = "" ]]; then #'nothing is open'
    echo "emacs$opts$add_opts"
elif [[ "$frame_exists" = "nil" ]]; then #'terminal is open'
    [[ "$add_opts" = "" ]] && add_opts=' -c'
    echo "emacsclient -e '(find-file \"$opts\")'$add_opts"
else #'frame(x-window) is open'
    echo "emacsclient -e '(find-file \"$opts\")'$add_opts"
fi
--MULTILINE-COMMENT--
