#!/bin/bash

for arg in "$@"
do
    serverp="-s"
    if [[ "$arg" =~ $serverp ]]; then
        server=true
    fi
done

frame_exists=`emacsclient -e "(member \"$DISPLAY\" (mapcar 'terminal-name (frames-on-display-list)))" 2>/dev/null`
if [[ "$server" = "" || "$frame_exists" = "" ]]; then
    `emacs $@`
else
    shift
    `emacsclient -n $@`
fi
